spring:
    resources:
        chain:
            cache: false
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
    datasource: 
        url: jdbc:postgresql://localhost:5432/bittrexgatherer
        username: postgres
        password: root